# wayvid Test Configuration
# 测试配置文件

source:
  type: File
  path: "/home/yangyus8/code/edupal/功能演示.mp4"

layout: Fill
loop: true
mute: true
volume: 0
hwdec: true
start: 0
speed: 1.0

# Power management (not enforced in M1)
power:
  pause_when_hidden: true
  pause_on_battery: false
  max_fps: 60
